spring:
  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      jdbc:
        time_zone: Asia/Seoul
      ddl-auto: update

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      url-prefix: ${WHISPY_AUDIO_FOLDER}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
